# Generated by Django 4.2.7 on 2025-08-29 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='nom',
            field=models.CharField(choices=[('non_defini', 'Non défini'), ('projet_de_developpement', ' Projet de developpement'), ('a_recruter', 'A recruter'), ('recrutement_en_cours', 'Recrutement en cours'), ('formation_en_cours', 'Formation en cours'), ('formation_a_annuler', 'Formation à annuler'), ('formation_a_repousser', 'Formation à repousser'), ('formation_annulee', 'Formation annulée'), ('pleine', 'Pleine'), ('quasi_pleine', 'Quasi-pleine'), ('autre', 'Autre')], help_text='Identifiant du statut parmi les choix prédéfinis', max_length=100, verbose_name='Nom du statut'),
        ),
        migrations.CreateModel(
            name='AtelierTREPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('statut', models.CharField(choices=[('inconnu', 'Non renseigné'), ('present', 'Présent'), ('absent', 'Absent'), ('excuse', 'Excusé')], default='inconnu', max_length=15, verbose_name='Statut de présence')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rap_app.ateliertre', verbose_name='Atelier')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_ateliers', to='rap_app.candidat', verbose_name='Candidat')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Présence à un atelier',
                'verbose_name_plural': 'Présences à des ateliers',
            },
        ),
        migrations.AddConstraint(
            model_name='ateliertrepresence',
            constraint=models.UniqueConstraint(fields=('atelier', 'candidat'), name='uniq_presence_atelier_candidat'),
        ),
    ]
