# Generated by Django 4.2.7 on 2025-05-10 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logutilisateur',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log utilisateur', 'verbose_name_plural': 'Logs utilisateurs'},
        ),
        migrations.AlterField(
            model_name='logutilisateur',
            name='action',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='logutilisateur',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_utilisateurs', to='contenttypes.contenttype', verbose_name="Type d'objet"),
        ),
        migrations.AlterField(
            model_name='logutilisateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='logutilisateur',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='logutilisateur',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='logutilisateur',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet"),
        ),
        migrations.AddIndex(
            model_name='logutilisateur',
            index=models.Index(fields=['content_type', 'object_id'], name='log_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='logutilisateur',
            index=models.Index(fields=['created_at'], name='log_date_idx'),
        ),
        migrations.AddIndex(
            model_name='logutilisateur',
            index=models.Index(fields=['action'], name='log_action_idx'),
        ),
    ]
