# Generated by Django 4.2.7 on 2025-07-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='origine_sourcing',
            field=models.CharField(blank=True, help_text='Comment le contact a été établi avec le candidat', max_length=255, null=True, verbose_name='Origine du sourcing'),
        ),
        migrations.AlterField(
            model_name='participationateliertre',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_ateliers', to='rap_app.candidat'),
        ),
    ]
