# Generated by Django 4.2.7 on 2025-05-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0002_alter_logutilisateur_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logutilisateur',
            new_name='rap_app_log_content_04adbe_idx',
            old_name='log_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='logutilisateur',
            new_name='rap_app_log_created_78479c_idx',
            old_name='log_date_idx',
        ),
        migrations.RenameIndex(
            model_name='logutilisateur',
            new_name='rap_app_log_action_3ca38c_idx',
            old_name='log_action_idx',
        ),
    ]
