# Generated by Django 4.2.7 on 2025-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0002_alter_statut_nom_ateliertrepresence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='centres',
            field=models.ManyToManyField(blank=True, help_text='Limite la visibilité des données pour ce membre du staff.', related_name='users', to='rap_app.centre', verbose_name='Centres autorisés'),
        ),
    ]
