# Generated by Django 4.2.7 on 2025-08-31 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_customuser_centres'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='default_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires_default', to='rap_app.centre', verbose_name='Centre par défaut'),
        ),
        migrations.AddField(
            model_name='prospection',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospections', to='rap_app.centre', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospections', to='rap_app.formation'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospections', to='rap_app.partenaire'),
        ),
        migrations.AddIndex(
            model_name='prospection',
            index=models.Index(fields=['owner'], name='rap_app_pro_owner_i_795327_idx'),
        ),
        migrations.AddIndex(
            model_name='prospection',
            index=models.Index(fields=['centre'], name='rap_app_pro_centre__754b86_idx'),
        ),
    ]
