# Generated by Django 4.2.7 on 2025-05-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_rename_log_obj_idx_rap_app_log_content_04adbe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueformation',
            name='formation',
            field=models.ForeignKey(blank=True, help_text='Formation à laquelle ce changement est associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='rap_app.formation', verbose_name='Formation concernée'),
        ),
    ]
