# Generated by Django 4.2.7 on 2025-07-12 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='communication',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Communication (étoiles)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='csp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='CSP (étoiles)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Expérience (étoiles)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrateur'), ('admin', 'Administrateur'), ('stagiaire', 'Stagiaire'), ('staff', 'Membre du staff'), ('test', 'Test'), ('candidat', 'candidat'), ('candidatuser', 'Candidat validé')], db_index=True, default='stagiaire', help_text="Rôle ou niveau d'accès de l'utilisateur", max_length=20, verbose_name='Rôle'),
        ),
    ]
