# Generated by Django 4.2.7 on 2025-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0004_partenaire_default_centre_prospection_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivijury',
            name='mois',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=9, help_text="Mois de l'année (1-12)", verbose_name='Mois'),
        ),
    ]
