# Generated by Django 4.2.7 on 2025-07-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0004_alter_candidat_communication_alter_candidat_csp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueplacement',
            options={'ordering': ['-date_placement'], 'verbose_name': 'Historique de placement', 'verbose_name_plural': 'Historique de placements'},
        ),
        migrations.RenameField(
            model_name='historiqueplacement',
            old_name='date',
            new_name='date_placement',
        ),
        migrations.AlterField(
            model_name='appairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'A faire')], default='transmis', max_length=20, verbose_name="Statut de l'appairage"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='compte_utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidat_associe', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='entretien_done',
            field=models.BooleanField(default=False, verbose_name='Entretien réalisé'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='origine_sourcing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origine du sourcing'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='rqth',
            field=models.BooleanField(default=False, verbose_name='RQTH'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('att_entretien', "En attente d'entretien"), ('att_commission', 'En attente de commission'), ('accompagnement', 'En accompagnement'), ('appairage', 'En appairage'), ('formation', 'En formation'), ('abandon', 'Abandon'), ('autre', 'Autre')], db_index=True, default='accompagnement', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='test_is_ok',
            field=models.BooleanField(default=False, verbose_name="Test d'entrée réussi"),
        ),
        migrations.AlterField(
            model_name='historiqueappairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'A faire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueplacement',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
    ]
