# Generated by Django 4.2.7 on 2025-09-02 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0005_alter_suivijury_mois'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('centre', 'Par centre'), ('user', 'Par utilisateur'), ('formation', 'Par formation')], db_index=True, default='global', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version du schéma de métriques')),
                ('kpis', models.JSONField(blank=True, default=dict)),
                ('series', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_snapshots', to='rap_app.centre')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text="Utilisateur ayant créé l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_snapshots', to='rap_app.formation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_snapshots', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Snapshot de dashboard',
                'verbose_name_plural': 'Snapshots de dashboard',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['scope', 'centre', 'owner', 'formation'], name='dash_scope_idx'), models.Index(fields=['period_start', 'period_end'], name='dash_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dashboardsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('period_start__lte', models.F('period_end'))), name='dashboard_period_coherent'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardsnapshot',
            unique_together={('scope', 'centre', 'owner', 'formation', 'period_start', 'period_end', 'version')},
        ),
    ]
