# Generated by Django 4.2.7 on 2025-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0005_alter_historiqueplacement_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ateliertre',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='participationateliertre',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ateliertre',
            constraint=models.UniqueConstraint(fields=('type_atelier', 'date'), name='unique_atelier_par_date'),
        ),
        migrations.AddConstraint(
            model_name='participationateliertre',
            constraint=models.UniqueConstraint(fields=('candidat', 'ateliertre'), name='unique_participation'),
        ),
    ]
