# Generated by Django 4.2.7 on 2025-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0006_dashboardsnapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardSnapshot',
        ),
    ]
