# Generated by Django 4.2.7 on 2025-07-13 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0006_alter_ateliertre_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historiqueprospection',
            new_name='rap_app_his_prospec_f00db9_idx',
            old_name='histprosp_prosp_idx',
        ),
        migrations.RenameIndex(
            model_name='historiqueprospection',
            new_name='rap_app_his_date_mo_5b61b9_idx',
            old_name='histprosp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historiqueprospection',
            new_name='rap_app_his_prochai_5f80db_idx',
            old_name='histprosp_next_idx',
        ),
        migrations.RenameIndex(
            model_name='historiqueprospection',
            new_name='rap_app_his_nouveau_6613e9_idx',
            old_name='histprosp_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_statut_84d25a_idx',
            old_name='prosp_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_date_pr_5d71cf_idx',
            old_name='prosp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_partena_379d92_idx',
            old_name='prosp_partenaire_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_formati_986a4a_idx',
            old_name='prosp_formation_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_created_4cb87b_idx',
            old_name='prosp_createdby_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_motif_a6b1c2_idx',
            old_name='prosp_motif_idx',
        ),
        migrations.RenameIndex(
            model_name='prospection',
            new_name='rap_app_pro_objecti_b08f76_idx',
            old_name='prosp_objectif_idx',
        ),
        migrations.AlterField(
            model_name='appairage',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du retour du partenaire'),
        ),
        migrations.AlterField(
            model_name='appairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'À faire')], default='transmis', max_length=20, verbose_name="Statut de l'appairage"),
        ),
        migrations.AlterField(
            model_name='historiqueappairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'À faire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='ancien_statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('non_renseigne', 'Non renseigné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='date_modification',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='moyen_contact',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('visite', 'Visite'), ('reseaux', 'Réseaux sociaux')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='nouveau_statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('non_renseigne', 'Non renseigné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='prochain_contact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='prospection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='rap_app.prospection', verbose_name='Prospection'),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='resultat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='type_contact',
            field=models.CharField(choices=[('premier_contact', 'Premier contact'), ('relance', 'Relance')], default='premier_contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='date_prospection',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospections', to='rap_app.formation', verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='motif',
            field=models.CharField(choices=[('POEI', 'POEI'), ('apprentissage', 'Apprentissage'), ('VAE', 'VAE'), ('partenariat', 'Établir un partenariat'), ('autre', 'Autre')], max_length=30, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='objectif',
            field=models.CharField(choices=[('prise_contact', 'Prise de contact'), ('rendez_vous', 'Obtenir un rendez-vous'), ('presentation_offre', "Présentation d'une offre"), ('contrat', 'Signer un contrat'), ('partenariat', 'Établir un partenariat'), ('autre', 'Autre')], default='prise_contact', max_length=30, verbose_name='Objectif'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospections', to='rap_app.partenaire', verbose_name='Partenaire'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('non_renseigne', 'Non renseigné')], default='a_faire', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='type_contact',
            field=models.CharField(choices=[('premier_contact', 'Premier contact'), ('relance', 'Relance')], default='premier_contact', max_length=20, verbose_name='Type de contact'),
        ),
    ]
