# Generated by Django 4.2.7 on 2025-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0007_delete_dashboardsnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prospection',
            name='prosp_acceptee_contrat',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('apprentissage', 'Apprentissage'), ('professionnalisation', 'Professionnalisation'), ('sans_contrat', 'Sans contrat'), ('poei_poec', 'POEI / POEC'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Type de contrat'),
        ),
        migrations.AddIndex(
            model_name='appairage',
            index=models.Index(fields=['candidat'], name='rap_app_app_candida_d22b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='appairage',
            index=models.Index(fields=['partenaire'], name='rap_app_app_partena_1d76fa_idx'),
        ),
        migrations.AddIndex(
            model_name='appairage',
            index=models.Index(fields=['formation'], name='rap_app_app_formati_9f7337_idx'),
        ),
        migrations.AddIndex(
            model_name='appairage',
            index=models.Index(fields=['statut'], name='rap_app_app_statut_949f91_idx'),
        ),
        migrations.AddIndex(
            model_name='appairage',
            index=models.Index(fields=['date_appairage'], name='rap_app_app_date_ap_9c0d62_idx'),
        ),
    ]
