# Generated by Django 4.2.7 on 2025-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0007_rename_histprosp_prosp_idx_rap_app_his_prospec_f00db9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueprospection',
            name='type_contact',
        ),
        migrations.RemoveField(
            model_name='prospection',
            name='type_contact',
        ),
        migrations.AddField(
            model_name='historiqueprospection',
            name='type_prospection',
            field=models.CharField(choices=[('nouveau_prospect', 'Nouveau prospect'), ('premier_contact', 'Premier contact'), ('relance', 'Relance'), ('reprise_contact', 'Reprise de contact'), ('suivi', 'Suivi en cours'), ('rappel_programme', 'Rappel programmé'), ('fidelisation', 'Fidélisation'), ('autre', 'Autre')], default='nouveau_prospect', max_length=20, verbose_name='Type de prospection'),
        ),
        migrations.AddField(
            model_name='prospection',
            name='type_prospection',
            field=models.CharField(choices=[('nouveau_prospect', 'Nouveau prospect'), ('premier_contact', 'Premier contact'), ('relance', 'Relance'), ('reprise_contact', 'Reprise de contact'), ('suivi', 'Suivi en cours'), ('rappel_programme', 'Rappel programmé'), ('fidelisation', 'Fidélisation'), ('autre', 'Autre')], default='premier_contact', max_length=20, verbose_name='Type de prospection'),
        ),
    ]
