# Generated by Django 4.2.7 on 2025-09-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0008_remove_prospection_prosp_acceptee_contrat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireAppairage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'objet est actif ou archivé", verbose_name='Actif')),
                ('body', models.TextField(verbose_name='Commentaire')),
                ('is_internal', models.BooleanField(default=False, help_text='Indique si le commentaire est réservé au staff interne', verbose_name='Interne ?')),
                ('statut_snapshot', models.CharField(blank=True, help_text='Statut de l’appairage figé au moment où le commentaire a été créé', max_length=20, null=True, verbose_name='Statut au moment du commentaire')),
                ('appairage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='rap_app.appairage', verbose_name='Appairage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_appairages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('updated_by', models.ForeignKey(blank=True, help_text="Dernier utilisateur ayant modifié l'enregistrement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Commentaire d’appairage',
                'verbose_name_plural': 'Commentaires d’appairages',
                'ordering': ['-created_at'],
            },
        ),
    ]
