# Generated by Django 4.2.7 on 2025-09-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0009_commentaireappairage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appairage',
            name='commentaire',
        ),
    ]
