# Generated by Django 4.2.7 on 2025-05-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0010_userprofile_logutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant créé ce partenaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
