# Generated by Django 4.2.7 on 2025-09-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0010_remove_appairage_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaireappairage',
            name='is_internal',
        ),
    ]
