# Generated by Django 4.2.7 on 2025-09-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0011_remove_commentaireappairage_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('apprentissage', 'Apprentissage'), ('professionnalisation', 'Professionnalisation'), ('sans_contrat', 'Sans contrat'), ('poei_poec', 'POEI / POEC'), ('crif', 'Crif'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='historiquestatutvae',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Notes ou informations supplémentaires', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='historiquestatutvae',
            name='date_changement_effectif',
            field=models.DateField(help_text='Date à laquelle le changement de statut a eu lieu', verbose_name='Date effective du changement'),
        ),
    ]
