# Generated by Django 4.2.7 on 2025-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0012_alter_candidat_type_contrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrateur'), ('admin', 'Administrateur'), ('stagiaire', 'Stagiaire'), ('staff', 'Membre du staff'), ('staff_read', 'Staff lecture seule'), ('test', 'Test'), ('candidat', 'Candidat'), ('candidatuser', 'Candidat validé')], db_index=True, default='stagiaire', help_text="Rôle ou niveau d'accès de l'utilisateur", max_length=20, verbose_name='Rôle'),
        ),
    ]
