# Generated by Django 4.2.7 on 2025-10-04 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0014_alter_candidat_compte_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='assurance_chomage_speciale',
            field=models.BooleanField(default=False, help_text="Cochez si l'employeur est soumis à un régime particulier (souvent public)", verbose_name='Assurance chômage spéciale'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='code_ape',
            field=models.CharField(blank=True, help_text="Code APE de l'entreprise", max_length=10, null=True, verbose_name='Code APE'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='effectif_total',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre total de salariés', null=True, verbose_name='Effectif total'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='email',
            field=models.EmailField(blank=True, help_text="Adresse email principale de l'entreprise", max_length=254, null=True, verbose_name='Email général'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='employeur_specifique',
            field=models.CharField(blank=True, help_text='Ex: artisan, profession libérale…', max_length=255, null=True, verbose_name='Employeur spécifique'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='idcc',
            field=models.CharField(blank=True, help_text='Code convention collective', max_length=10, null=True, verbose_name='IDCC'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_courriel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Maître d’apprentissage n°1 - Courriel'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Maître d’apprentissage n°1 - Date de naissance'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_diplome_titre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maître d’apprentissage n°1 - Diplôme ou titre le plus élevé obtenu'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_emploi_occupe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maître d’apprentissage n°1 - Emploi occupé'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_niveau_diplome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maître d’apprentissage n°1 - Niveau de diplôme ou titre le plus élevé obtenu'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_nom_naissance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Maître d’apprentissage n°1 - Nom de naissance'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre1_prenom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Maître d’apprentissage n°1 - Prénom'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_courriel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Maître d’apprentissage n°2 - Courriel'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Maître d’apprentissage n°2 - Date de naissance'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_diplome_titre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maître d’apprentissage n°2 - Diplôme ou titre le plus élevé obtenu'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_emploi_occupe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maître d’apprentissage n°2 - Emploi occupé'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_niveau_diplome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maître d’apprentissage n°2 - Niveau de diplôme ou titre le plus élevé obtenu'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_nom_naissance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Maître d’apprentissage n°2 - Nom de naissance'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='maitre2_prenom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Maître d’apprentissage n°2 - Prénom'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='siret',
            field=models.CharField(blank=True, help_text='Numéro SIRET (14 chiffres)', max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Le SIRET doit comporter 14 chiffres.')], verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='street_complement',
            field=models.CharField(blank=True, help_text='Bâtiment, étage, entrée, etc.', max_length=255, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='street_number',
            field=models.CharField(blank=True, help_text='Numéro dans la voie (ex: 12B)', max_length=10, null=True, verbose_name='Numéro de rue'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='telephone',
            field=models.CharField(blank=True, help_text="Numéro de téléphone principal de l'entreprise", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Entrez un numéro de téléphone français valide.', regex='^(0[1-9]\\d{8})$|^(?:\\+33|0033)[1-9]\\d{8}$')], verbose_name='Téléphone général'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='type_employeur',
            field=models.CharField(blank=True, choices=[('prive', 'Privé'), ('public', 'Public')], help_text="Définit si l'employeur est privé ou public", max_length=20, null=True, verbose_name="Type d'employeur"),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='street_name',
            field=models.CharField(blank=True, help_text='Nom de la rue', max_length=200, null=True, verbose_name='Adresse'),
        ),
    ]
