# Generated by Django 4.2.7 on 2025-10-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0015_partenaire_assurance_chomage_speciale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='commune_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='departement_naissance',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='dernier_diplome_prepare',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dernier diplôme préparé'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='derniere_classe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dernière classe fréquentée'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplome_plus_eleve_obtenu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diplôme ou titre le plus élevé obtenu'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='equivalence_jeunes',
            field=models.BooleanField(default=False, verbose_name='Equivalence jeune?'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='extension_boe',
            field=models.BooleanField(default=False, verbose_name='Extension BOE?'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='intitule_diplome_prepare',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Intitulé du diplôme préparé'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='nationalite',
            field=models.CharField(blank=True, default='Française', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='nir',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de sécurité sociale (NIR)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='nom_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='pays_naissance',
            field=models.CharField(blank=True, default='France', max_length=100, null=True, verbose_name='Pays de naissance'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='projet_creation_entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidat',
            name='regime_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Régime social (Sécurité sociale)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune du représentant légal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel du représentant légal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_lien',
            field=models.CharField(blank=True, help_text='Ex. père, mère, tuteur, autre', max_length=50, null=True, verbose_name='Lien avec le candidat'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_nom_naissance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de naissance du représentant légal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_prenom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom du représentant légal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_street_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du représentant légal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='representant_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal du représentant légal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='situation_actuelle',
            field=models.CharField(blank=True, help_text='Ex. demandeur d’emploi, lycéen, salarié…', max_length=255, null=True, verbose_name='Situation avant ce contrat'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='situation_avant_contrat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Situation avant le contrat'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='sportif_haut_niveau',
            field=models.BooleanField(default=False, verbose_name='Sportif de haut niveau?'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='street_complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la rue'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de voie'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="Nom d'usage"),
        ),
    ]
