# Generated by Django 4.2.7 on 2025-10-05 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0016_candidat_commune_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international (+33612345678) ou national (0612345678).', regex='^\\+?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
    ]
