# Generated by Django 4.2.7 on 2025-10-05 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0017_alter_candidat_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='cfa_entreprise',
            field=models.BooleanField(default=False, help_text='CFA d’entreprise'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_complement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_denomination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dénomination du CFA responsable'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_est_lieu_principal',
            field=models.BooleanField(default=False, help_text='Si le CFA responsable est le lieu de formation principal'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_siret',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='N° SIRET du CFA'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_uai',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° UAI du CFA'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cfa_responsable_voie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='complement_adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément adresse'),
        ),
        migrations.AddField(
            model_name='centre',
            name='nom_voie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la voie'),
        ),
        migrations.AddField(
            model_name='centre',
            name='numero_uai_centre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='numero_voie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de voie'),
        ),
        migrations.AddField(
            model_name='centre',
            name='siret_centre',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit comporter 10 chiffres et commencer par 0 (ex : 0612345678).', regex='^0\\d{9}$')], verbose_name='Téléphone'),
        ),
    ]
