# Generated by Django 4.2.7 on 2025-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0018_centre_cfa_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
