# Generated by Django 4.2.7 on 2025-10-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0019_centre_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='code_diplome',
            field=models.CharField(blank=True, help_text='Code du diplôme visé par la formation', max_length=50, null=True, verbose_name='Code diplôme'),
        ),
        migrations.AddField(
            model_name='formation',
            name='code_rncp',
            field=models.CharField(blank=True, help_text='Code RNCP du diplôme', max_length=50, null=True, verbose_name='Code RNCP'),
        ),
        migrations.AddField(
            model_name='formation',
            name='heures_distanciel',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'heures effectuées à distance", null=True, verbose_name='Heures en distanciel'),
        ),
        migrations.AddField(
            model_name='formation',
            name='intitule_diplome',
            field=models.CharField(blank=True, help_text='Intitulé précis du diplôme ou titre préparé', max_length=255, null=True, verbose_name='Diplôme ou titre visé par l’apprenti'),
        ),
        migrations.AddField(
            model_name='formation',
            name='total_heures',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre total d'heures de formation en présentiel + distanciel", null=True, verbose_name='Durée totale (heures)'),
        ),
    ]
