# Generated by Django 4.2.7 on 2025-10-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0020_formation_code_diplome_formation_code_rncp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ateliertrepresence',
            name='statut',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('excuse', 'Excusé'), ('inconnu', 'Non renseigné')], default='inconnu', max_length=15, verbose_name='Statut de présence'),
        ),
    ]
