# Generated by Django 4.2.7 on 2025-10-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0021_alter_ateliertrepresence_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='nom',
            field=models.CharField(choices=[('non_defini', 'Non défini'), ('projet_de_developpement', 'Projet de développement'), ('a_recruter', 'À recruter'), ('recrutement_en_cours', 'Recrutement en cours'), ('formation_en_cours', 'Formation en cours'), ('formation_a_annuler', 'Formation à annuler'), ('formation_a_repousser', 'Formation à repousser'), ('formation_annulee', 'Formation annulée'), ('formation_annulee_archivee', 'Formation annulée (archivée)'), ('archivee', 'Archivée'), ('pleine', 'Pleine'), ('quasi_pleine', 'Quasi-pleine'), ('autre', 'Autre')], help_text='Identifiant du statut parmi les choix prédéfinis', max_length=100, verbose_name='Nom du statut'),
        ),
    ]
