# Generated by Django 4.2.7 on 2025-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0022_alter_statut_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'À faire'), ('contrat_a_signer', 'Contrat à signer'), ('contrat_en_attente', 'Contrat en attente'), ('appairage_ok', 'Appairage OK'), ('archive', 'Archivé')], default='transmis', max_length=30, verbose_name="Statut de l'appairage"),
        ),
        migrations.AlterField(
            model_name='historiqueappairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'À faire'), ('contrat_a_signer', 'Contrat à signer'), ('contrat_en_attente', 'Contrat en attente'), ('appairage_ok', 'Appairage OK'), ('archive', 'Archivé')], max_length=30),
        ),
    ]
