# Generated by Django 4.2.7 on 2025-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0023_alter_appairage_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueprospection',
            name='ancien_statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('archivee', 'Archivée'), ('non_renseigne', 'Non renseigné')], max_length=20, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='historiqueprospection',
            name='nouveau_statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('archivee', 'Archivée'), ('non_renseigne', 'Non renseigné')], max_length=20, verbose_name='Nouveau statut'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('a_relancer', 'À relancer'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('archivee', 'Archivée'), ('non_renseigne', 'Non renseigné')], default='a_faire', max_length=20, verbose_name='Statut'),
        ),
    ]
