# Generated by Django 4.2.7 on 2025-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0025_prospection_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appairage',
            name='activite',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], db_index=True, default='actif', max_length=10, verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='appairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'À faire'), ('contrat_a_signer', 'Contrat à signer'), ('contrat_en_attente', 'Contrat en attente'), ('appairage_ok', 'Appairage OK')], default='transmis', max_length=30, verbose_name="Statut de l'appairage"),
        ),
        migrations.AlterField(
            model_name='historiqueappairage',
            name='statut',
            field=models.CharField(choices=[('transmis', 'Transmis au partenaire'), ('en_attente', 'En attente de réponse'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé'), ('a_faire', 'À faire'), ('contrat_a_signer', 'Contrat à signer'), ('contrat_en_attente', 'Contrat en attente'), ('appairage_ok', 'Appairage OK')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='appairage',
            index=models.Index(fields=['activite'], name='rap_app_app_activit_b40b92_idx'),
        ),
    ]
