# Generated by Django 4.2.7 on 2025-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0027_formation_activite_alter_statut_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectioncomment',
            name='statut_commentaire',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], db_index=True, default='actif', help_text='Permet d’archiver logiquement un commentaire sans le supprimer.', max_length=20, verbose_name='Statut du commentaire'),
        ),
        migrations.AddIndex(
            model_name='prospectioncomment',
            index=models.Index(fields=['statut_commentaire'], name='rap_app_pro_statut__a09564_idx'),
        ),
    ]
