# Generated by Django 4.2.7 on 2025-10-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0028_prospectioncomment_statut_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaireappairage',
            name='statut_commentaire',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], db_index=True, default='actif', help_text='Permet d’archiver ou de restaurer logiquement un commentaire.', max_length=20, verbose_name='Statut du commentaire'),
        ),
        migrations.AlterField(
            model_name='commentaireappairage',
            name='statut_snapshot',
            field=models.CharField(blank=True, help_text='Statut de l’appairage figé au moment où le commentaire a été créé.', max_length=20, null=True, verbose_name='Statut au moment du commentaire'),
        ),
        migrations.AddIndex(
            model_name='commentaireappairage',
            index=models.Index(fields=['appairage'], name='rap_app_com_appaira_7febfd_idx'),
        ),
        migrations.AddIndex(
            model_name='commentaireappairage',
            index=models.Index(fields=['created_by'], name='rap_app_com_created_9fc2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='commentaireappairage',
            index=models.Index(fields=['statut_commentaire'], name='rap_app_com_statut__0f6600_idx'),
        ),
        migrations.AddIndex(
            model_name='commentaireappairage',
            index=models.Index(fields=['created_at'], name='rap_app_com_created_8f6e2d_idx'),
        ),
    ]
