# Generated by Django 4.2.7 on 2025-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0029_commentaireappairage_statut_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='statut_commentaire',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], db_index=True, default='actif', help_text='Permet d’archiver ou de restaurer logiquement un commentaire.', max_length=20, verbose_name='Statut du commentaire'),
        ),
    ]
