# Generated by Django 4.2.7 on 2025-10-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0030_commentaire_statut_commentaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectioncomment',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Commentaire de prospection', 'verbose_name_plural': 'Commentaires de prospection'},
        ),
    ]
