# Generated by Django 4.2.7 on 2025-10-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0032_cerfacontrat_cerfaremuneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfacontrat',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Indique si le CERFA a été créé automatiquement (via signal).'),
        ),
    ]
