# Generated by Django 4.2.7 on 2025-10-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0033_cerfacontrat_auto_generated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cerfacontrat',
            options={'ordering': ['-created_at'], 'verbose_name': 'CERFA Contrat complet'},
        ),
        migrations.AlterModelOptions(
            name='cerfaremuneration',
            options={'ordering': ['annee', 'date_debut'], 'verbose_name': 'Rémunération CERFA'},
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='age_apprenti',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='attestation_pieces_justificatives',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='avantages_en_nature_total',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='cfa_code_postal',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='cfa_complement',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='cfa_entreprise',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='cfa_lieu_principal',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='cfa_numero',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='cfa_voie',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='date_debut_formation',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='date_effet_avenant',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='duree_hebdo_minutes',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='duree_totale_contrat_mois',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='employeur',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='formation_lieu_complement',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='formation_lieu_numero',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='motif_derogation',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='numero_contrat_precedent',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='ref_salaire',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='representant_adresse_complement',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='representant_adresse_numero',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='signature_representant_legal',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='travail_dangereux',
        ),
        migrations.RemoveField(
            model_name='cerfacontrat',
            name='type_derogation',
        ),
        migrations.RemoveField(
            model_name='cerfaremuneration',
            name='contrat',
        ),
        migrations.AddField(
            model_name='cerfaremuneration',
            name='contrat_id',
            field=models.IntegerField(blank=True, help_text='ID du contrat (rempli manuellement si besoin)', null=True),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='apprenti_nom_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='apprenti_prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='employeur_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerfacontrat',
            name='representant_lien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cerfaremuneration',
            name='annee',
            field=models.PositiveSmallIntegerField(choices=[(1, '1ère année'), (2, '2e année'), (3, '3e année')]),
        ),
        migrations.AlterField(
            model_name='cerfaremuneration',
            name='montant_mensuel_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
