# Generated by Django 4.2.7 on 2025-10-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0034_alter_cerfacontrat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_rgpd',
            field=models.BooleanField(default=False),
        ),
    ]
